"""add resolution logs

Revision ID: 001460d0a331
Revises: d77f6ff273c9
Create Date: 2026-10-04 17:13:48.899985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001460d0a331'
down_revision: Union[str, Sequence[str], None] = 'd77f6ff273c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('sub_intent', sa.String(length=150), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.Column('authoritative_evidence_count', sa.Integer(), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('unsupported_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution_confidence', sa.Float(), nullable=False),
    sa.Column('resolution_summary', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolution_logs')
    # ### end Alembic commands ###
