"""add conversation domain tables

Revision ID: c09dc44bcbe6
Revises: 31a3f4afe9e4
Create Date: 2026-10-03 12:56:38.171203

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c09dc44bcbe6"
down_revision: str | Sequence[str] | None = "31a3f4afe9e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("product", sa.String(length=100), nullable=True),
        sa.Column("intent", sa.String(length=100), nullable=True),
        sa.Column("sub_intent", sa.String(length=100), nullable=True),
        sa.Column("sentiment", sa.String(length=50), nullable=True),
        sa.Column("severity", sa.String(length=50), nullable=True),
        sa.Column(
            "resolution_status",
            sa.Enum(
                "RESOLVED",
                "ESCALATED",
                "UNRESOLVED",
                "UNKNOWN",
                name="resolution_status",
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column(
            "quality_status",
            sa.Enum(
                "VALID",
                "INCOMPLETE",
                "DUPLICATE",
                "LOW_QUALITY",
                "SENSITIVE",
                "REVIEW",
                name="quality_status",
            ),
            server_default="REVIEW",
            nullable=False,
        ),
        sa.Column("source_dataset", sa.String(length=100), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_dataset",
            "dataset_version",
            "external_id",
            name="uq_conversations_source_version_external",
        ),
    )
    op.create_index(
        "ix_conversations_intent", "conversations", ["intent"], unique=False
    )
    op.create_index(
        "ix_conversations_product", "conversations", ["product"], unique=False
    )
    op.create_index(
        "ix_conversations_resolution_status",
        "conversations",
        ["resolution_status"],
        unique=False,
    )
    op.create_table(
        "conversation_turns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column(
            "speaker", sa.Enum("CLIENT", "AGENT", name="speaker"), nullable=False
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id",
            "turn_index",
            name="uq_conversation_turns_conversation_index",
        ),
    )
    op.create_index(
        "ix_conversation_turns_conversation_id",
        "conversation_turns",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_conversation_turns_conversation_id", table_name="conversation_turns"
    )
    op.drop_table("conversation_turns")
    op.drop_index("ix_conversations_resolution_status", table_name="conversations")
    op.drop_index("ix_conversations_product", table_name="conversations")
    op.drop_index("ix_conversations_intent", table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
